### ISSUE TITLE
[Feature Request] Persistent file state

### ISSUE THREAD

**Issue by yan42685** [ludovicchabant/obsidian-remember-file-state#11]
The state info seems to be lost after closing obsidian. It will be nice if this plugin can store the state info in a local file and load it when this plugin is loaded.

**Comment by ludovicchabant** [comment]
Hi!
Yep this is an often-requested feature. I haven't looked into how to do it yet but if anybody wants to take a stab at it in a PR I'd gladly review it.

**Comment by 5HT2** [comment]
The way that vim does this, is that it has the `~/.cache/vim/` folder, with 3 folders: backup, swap, undo. 

The "undo history" is a similar concept to this as saving cursor position and selection, and vim also remembers these things.

The way it does this is by saving the config for each file as a text file in `~/.cache/vim/undo/`, with the full file path as the file name (with path separators changed to a `%`, for example: `%home%frog%projects%fs-over-http%USAGE.md`).

The other way to do this is save `this.data` to a file of it's own. I'm not sure why you're using viewID instead of keeping track of the file path? But using `string` as getting the state when re-opening a file would work. You can just save that as a parameter in the plugin settings. I'm sure there's better ways, but using a Record with a key (no need to loop through to find your state) is as efficient as most plugins.
```diff
-	// Interface for all currently remembered file states.
-	interface RememberFileStatePluginData {
-		rememberedFiles: Record<string, RememberedFileState>;
-	}

	export interface RememberFileStatePluginSettings {
		rememberMaxFiles: number;
+		rememberedFiles: Record<string, RememberedFileState>;
	}
```

**Comment by ludovicchabant** [comment]
[Version 1.1.0](https://github.com/ludovicchabant/obsidian-remember-file-state/releases/tag/1.1.0) now implements this!

I'm indeed just serializing `this.data`, where state is mapped to the relative vault path of each file. The view IDs are just temporary, to figure what's what, and not meant to be persisted between sessions.
