### ISSUE TITLE
Plugin causes "Reload app without saving" to just close the app (and not reload)

### ISSUE THREAD

**Issue by ReaderGuy42** [ludovicchabant/obsidian-remember-file-state#16]
I tested this in the sandbox vault with the same result: When this plugin is active and you use the command to "Reload app without saving", Obsidian just closes and doesn't reload or reopen.

Thanks!

**Comment by ludovicchabant** [comment]
Hi!  Indeed, it seems to close or crash Obsidian... after some lengthy investigation, however, I think it's an Obsidian bug. AFAICT, if a callback on [the app quit event][1] adds a promise to the [given task queue][2], then it closes Obsidian on reload. This is regardless of what the promise does -- even an empty function causes this. Running the same code synchronously (instead of queuing it as a task) makes reloading work, but breaks the normal quitting flow, which doesn't seem to wait on anything unless it's queued... its weird and I don't know what's going on, but, well, like I said, it looks like an Obsidian bug... although it's very possible I'm doing something stupid because I don't know Javascript that well. If anybody has any suggestions, I'll gladly take them!

[1]: https://docs.obsidian.md/Reference/TypeScript+API/Workspace/on_14 
[2]: https://docs.obsidian.md/Reference/TypeScript+API/Tasks/addPromise

**Comment by ludovicchabant** [comment]
I changed the code to work around the issue by running all the shutdown code synchronously :(  (see f7729fe5ddf1166e8bf3ae5921c212b1cff2040b). So this should be fixed with the newly release version 1.1.1.

**Comment by Mikestriken** [comment]
> I changed the code to work around the issue by running all the shutdown code synchronously :( (see [f7729fe](https://github.com/ludovicchabant/obsidian-remember-file-state/commit/f7729fe5ddf1166e8bf3ae5921c212b1cff2040b)). So this should be fixed with the newly release version 1.1.1.

Issue persists in version 1.1.2.
